default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: db

development:
  <<: *default
  database: Rails_Autodeploy_development 

test:
  <<: *default
  database: Rails_Autodeploy_test

production:
  <<: *default
  database: <%= ENV['DB_DATABASE'] %>
  username: sample_app
  password: <%= ENV['SAMPLE_DATABASE_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>